carefirst:
  account_id: "375299851423"
  region: "us-east-1"
  tags:
    TenantName: carefirst
    Environment: prod
    DataClass: confidential
    Owner: DevOps
  s3_bucket_suffix: "-prod"

  redshift:
    cluster_identifier: "carefirst-prod-cluster"
    cluster_type: "multi-node"
    node_type: "ra3.large"
    number_of_nodes: 3
    master_username: "admin"
    database_name: "carefirst_prod_db"
    secret_name: "carefirst-prod-redshift-secret"

  vpc:
    cidr: "10.20.0.0/16"
    max_azs: 2
    subnets:
      - name: "PublicSubnetA"
        cidr_mask: 24
        type: "PUBLIC"
      - name: "PublicSubnetB"
        cidr_mask: 24
        type: "PUBLIC"
      - name: "PrivateSubnetA"
        cidr_mask: 24
        type: "PRIVATE_WITH_EGRESS"
      - name: "PrivateSubnetB"
        cidr_mask: 24
        type: "PRIVATE_WITH_EGRESS"
