name: Deploy Redshift CDK

on:
  workflow_dispatch:
    inputs:
      tenant:
        description: 'Tenant name'
        required: true
        default: 'carefirst'
      env:
        description: 'Environment name (dev/prod)'
        required: true
        default: 'dev'

jobs:
  deploy:
    name: Deploy Redshift Stack
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
      CDK_DEFAULT_REGION: us-east-1

    steps:
      # 1. Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # 3. Install Python dependencies from redshift folder
      - name: Install Python dependencies
        working-directory: ./redshift
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Setup AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 5. Install CDK CLI
      - name: Install AWS CDK
        run: npm install -g aws-cdk

      # 6. Deploy Redshift Stack
      - name: Deploy Redshift
        working-directory: ./redshift
        run: |
          cdk deploy \
          -c tenant=${{ github.event.inputs.tenant }} \
          -c env=${{ github.event.inputs.env }} \
          --require-approval never

      # 7. Output stack info (optional)
      - name: List CDK Outputs
        working-directory: ./redshift
        run: cdk list
