name: Deploy Redshift CDK

on:
  workflow_dispatch:
    inputs:
      tenant:
        description: 'Tenant name'
        required: true
        default: 'carefirst'
      env:
        description: 'Environment (dev/prod)'
        required: true
        default: 'dev'

jobs:
  deploy-redshift:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # 3. Install dependencies inside redshift folder
      - name: Install dependencies
        working-directory: ./redshift
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Set up Node.js for CDK
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 5. Install AWS CDK CLI
      - name: Install CDK CLI
        run: npm install -g aws-cdk

      # 6. Deploy Redshift stack
      - name: Deploy Redshift CDK
        working-directory: ./redshift
        run: cdk deploy -c tenant=${{ github.event.inputs.tenant }} -c env=${{ github.event.inputs.env }} --require-approval never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
